apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx
data:
  default.conf:
      server {
        listen       9090;
        listen  [::]:9090;
        server_name  localhost;

        location / {
          root   /usr/share/nginx/html;
          index  index.html index.htm;
        }

        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
          root   /usr/share/nginx/html;
        }
      }
  index.html:
    <!DOCTYPE html>
    <html>
    <head>
    <title>Welcome to Netology</title>
    </head>
    <body>
    <h1>Hello, Netology!</h1>
    </body>
    </html>