apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-{{ .Values.appVersion | replace "." "-" }}-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-{{ .Values.appVersion | replace "." "-" }}
  template:
    metadata:
      labels:
        app: frontend-{{ .Values.appVersion | replace "." "-" }}
    spec:
      containers:
        - name: frontend-{{ .Values.appVersion | replace "." "-" }}
          image: "{{ .Values.fronted.image.repository }}:{{ .Values.fronted.image.tag }}"