apiVersion: v1
kind: Service
metadata:
  name: backend-{{ .Values.appVersion | replace "." "-" }}-svc
spec:
  selector:
    app: backend-{{ .Values.appVersion | replace "." "-" }}
  ports:
    - protocol: TCP
      port: 80
