apiVersion: v1
kind: Service
metadata:
  name: frontend-{{ .Values.appVersion | replace "." "-" }}-svc
spec:
  selector:
    app: frontend-{{ .Values.appVersion | replace "." "-" }}
  ports:
    - protocol: TCP
      port: 80