apiVersion: v1
kind: Pod
metadata:
  name: netology-web
  labels:
    app: netology-web
spec:
  containers:
  - image: gcr.io/kubernetes-e2e-test-images/echoserver:2.2
    name: netology-web
    resources:
      limits:
        cpu: 0.5
        memory: 100Mi
    ports:
        - containerPort: 8080
  automountServiceAccountToken: false