apiVersion: v1
kind: Pod
metadata:
  name: hello-world
  labels:
    app: hello-world
spec:
  containers:
  - image: gcr.io/kubernetes-e2e-test-images/echoserver:2.2
    name: hello-world
    resources:
      limits:
        cpu: 0.5
        memory: 100Mi
    ports:
        - containerPort: 8080
  automountServiceAccountToken: false