apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-multitool-dep
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-multitool
  template:
    metadata:
      labels:
        app: nginx-multitool
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
          - containerPort: 80
            protocol: TCP
        - name: multitool
          image: wbitt/network-multitool
          env:
          - name: HTTP_PORT
            value: "8080"
          ports:
          - containerPort: 8080
            protocol: TCP