apiVersion: v1
kind: Service
metadata:
  name: nginx-multitool-svc
spec:
  selector:
    app: nginx-multitool
  ports:
    - name: multitool-8080
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: nginx-80
      protocol: TCP
      port: 80
      targetPort: 80